server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
    #context-path: /kitty-admin
# DataSource
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.24.47.239:3306/hotel?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=true
#      url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: admin!#%123
#      password: hotel123
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot admin
  application:
    name: hotel-admin
  #redis
  redis:
    host: 118.24.47.239
    password: redis!#%123
    port: 6379
    database: 10
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 2
        max-wait: 10000
      shutdown-timeout: 100
    timeout: 5000
# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#mybatis
mybatis:
  type-aliases-package: com.hotel.admin.entity,com.hotel.admin.model
  mapper-locations: classpath:com/hotel/admin/mapper/xml/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  file: ./logs/hotel-log.log
  level:
    com.hotel.admin.mapper: debug
mapper:
  mappers: com.hotel.core.mybatis.mapper.AbstractMapper
  identity: MYSQL
  not-empty: false